### ISSUE TITLE
Weird JSON output

### ISSUE THREAD

**Issue by 000yesnt** [SizzlingStats/demboyz#12]
The DEM->JSON output has a weird structure, making it unreadable by default on other programs.
```
~/demboyz/bin$ LD_LIBRARY_PATH="./:$LD_LIBRARY_PATH" ./demboyz upward.dem upward.json
~/demboyz/bin$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> with open("upward.json") as f:
...     dem = json.load(f)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 15 column 2 (char 403)
```
<details>
<summary>A small sample of upward.json</summary>

```
{
    "demoheader": {
        "demofilestamp": "HL2DEMO",
        "demoprotocol": 3,
        "networkprotocol": 24,
        "servername": "AA Match",
        "clientname": "SourceTV Demo",
        "mapname": "pl_upward",
        "gamedirectory": "tf",
        "playback_time": 2740.155029296875,
        "playback_ticks": 182677,
        "playback_frames": 176851,
        "signonlength": 822337
    }
}{
    "cmd": 1,
    "tick": 40084
}{
    "democmdinfo": {
        "flags": 0,
        "viewOrigin": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
        },
        "viewAngles": {
            "pitch": 0.0,
            "yaw": 0.0,
            "roll": 0.0
        },
        "localViewAngles": {
            "pitch": 0.0,
            "yaw": 0.0,
            "roll": 0.0
        },
        "viewOrigin2": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
        },
        "viewAngles2": {
            "pitch": 0.0,
            "yaw": 0.0,
            "roll": 0.0
        },
        "localViewAngles2": {
            "pitch": 0.0,
            "yaw": 0.0,
            "roll": 0.0
        }
    },
    "sequenceNum1": 38695,
    "sequenceNum2": 38695
}{
    "netpacket": 8
}{
    "protocol": 24,
    "serverCount": 2,
    "isHltv": true,
    "isDedicated": true,
    "clientCrc": 4294967295,
    "maxClasses": 362,
    "unk1": "lV7puxks/56aFr+GThz7iw==",
    "playerSlot": 0,
    "maxClients": 33,
    "tickInterval": 0.014999999664723874,
    "os": "w",
    "gameDir": "tf",
    "mapName": "pl_upward",
    "skyName": "sky_upward",
    "hostName": "SourceTV",
    "unk2": false
}{
    "netpacket": 3
}{
    "tick": 67,
    "hostFrameTime": 0,
    "hostFrameTimeStdDev": 0
}{
    "netpacket": 12
}{
    "isFilenames": false,
    "tableName": "downloadables",
    "maxEntries": 8192,
    "numEntries": 1,
    "dataLengthInBits": 156,
    "isUserDataFixedSize": false,
    "userDataSize": 0,
    "userDataSizeBits": 0,
    "compressedData": false,
    "data": "awuDm+OCY/uqg7sLkyNzEZuDAwA="
}{
    "netpacket": 12
}{
    "isFilenames": false,
    "tableName": "modelprecache",
    "maxEntries": 4096,
    "numEntries": 947,
    "dataLengthInBits": 98784,
    "isUserDataFixedSize": true,
    "userDataSize": 1,
    "userDataSizeBits": 2,
    "compressedData": true,
    "data": "(truncated to reduce size)"
}{
    "netpacket": 12
}{
    "isFilenames": false,
    "tableName": "genericprecache",
    "maxEntries": 512,
    "numEntries": 1,
    "dataLengthInBits": 14,
    "isUserDataFixedSize": true,
    "userDataSize": 1,
    "userDataSizeBits": 2,
    "compressedData": false,
    "data": "Awg="
}{
    "netpacket": 12
}{
    "isFilenames": false,
    "tableName": "soundprecache",
    "maxEntries": 16384,
    "numEntries": 6516,
    "dataLengthInBits": 308864,
    "isUserDataFixedSize": true,
    "userDataSize": 1,
    "userDataSizeBits": 2,
    "compressedData": true,
    "data": "(truncated to reduce size)"
}{
    "netpacket": 12
}{
    "isFilenames": false,
    "tableName": "decalprecache",
    "maxEntries": 512,
    "numEntries": 133,
    "dataLengthInBits": 10638,
    "isUserDataFixedSize": true,
    "userDataSize": 1,
    "userDataSizeBits": 2,
    "compressedData": false,
    "data": "(truncated to reduce size)"
}{
    "netpacket": 12
}{
    "isFilenames": false,
    "tableName": "instancebaseline",
    "maxEntries": 1024,
    "numEntries": 31,
    "dataLengthInBits": 27064,
    "isUserDataFixedSize": false,
    "userDataSize": 0,
    "userDataSizeBits": 0,
    "compressedData": true,
    "data": "(truncated to reduce size)"
}{
    "netpacket": 12
}{
    "isFilenames": false,
    "tableName": "lightstyles",
    "maxEntries": 64,
    "numEntries": 64,
    "dataLengthInBits": 4676,
    "isUserDataFixedSize": false,
    "userDataSize": 0,
    "userDataSizeBits": 0,
    "compressedData": false,
    "data": "(truncated to reduce size)"
}{
    "netpacket": 12
}{
```

</details>

The packets don't have a parent object nor commas to separate them, This makes parsing the json file harder.

I'd try to fix it and make a PR, but [I'm waiting on Github to detach my existing fork](https://github.com/000yesnt/libdemboyz), and I don't have much C++ experience.

My demboyz binary was built on WSL2 (Ubuntu 22.04 LTS) by manually running ``gmake.sh`` and ``make`` inside the gmake dir.

**Comment by SizzlingCalamari** [comment]
It's intended that the .json output is a string of separate json objects.
You should be able to read them in order, just don't try to treat the whole
file as a single json object.

The idea behind this output format was to be able to stream it somewhere
piece by piece. It also keeps memory usage down when parsing.

**Comment by SizzlingCalamari** [comment]
Feel free to modify and submit a pull request if a different method works better for you.
